//! Phase 2 R5 marker hardening: generated marker comments must survive
//! `rustfmt` and remain scannable afterwards.

use std::process::Command;

use sunscreen::rustpatch::{scan, MarkerKind};

const FIXTURE: &str = r#"
use anchor_lang::prelude::*;

pub mod instructions {
// === sunscreen:auto-generated:begin segment=instructions version=1 generator=cli ===
pub mod initialize;
pub use initialize::*;
// === sunscreen:auto-generated:end segment=instructions ===
}

pub mod state {
// === sunscreen:auto-generated:begin segment=accounts version=1 generator=account ===
#[account]
pub struct Vault {
pub authority: Pubkey,
}
// === sunscreen:auto-generated:end segment=accounts ===
}

pub mod events {
// === sunscreen:auto-generated:begin segment=events version=1 generator=event ===
#[event]
pub struct Deposited {
pub amount: u64,
}
// === sunscreen:auto-generated:end segment=events ===
}

pub mod errors {
#[error_code]
pub enum DemoError {
// === sunscreen:auto-generated:begin segment=error_variants version=1 generator=error ===
#[msg("bad input")]
BadInput,
// === sunscreen:auto-generated:end segment=error_variants ===
}
}

#[program]
pub mod demo {
use super::*;

// === sunscreen:auto-generated:begin segment=dispatch version=1 generator=cli ===
pub fn initialize(ctx: Context<Initialize>, amount: u64) -> Result<()> {
instructions::initialize::handler(ctx, amount)
}
// === sunscreen:auto-generated:end segment=dispatch ===
}

pub mod initialize {
use super::*;

// === sunscreen:auto-generated:begin segment=file version=1 generator=instruction ===
#[derive(Accounts)]
pub struct Initialize<'info> {
pub signer: Signer<'info>,
}
// === sunscreen:auto-generated:end segment=file ===

pub fn handler(ctx: Context<Initialize>, amount: u64) -> Result<()> {
// === sunscreen:user-region:begin segment=handler ===
let _ = (ctx, amount);
Ok(())
// === sunscreen:user-region:end segment=handler ===
}
}
"#;

#[test]
fn documented_markers_survive_rustfmt_roundtrip() {
    let expected = [
        (MarkerKind::AutoGenerated, "instructions"),
        (MarkerKind::AutoGenerated, "accounts"),
        (MarkerKind::AutoGenerated, "events"),
        (MarkerKind::AutoGenerated, "error_variants"),
        (MarkerKind::AutoGenerated, "dispatch"),
        (MarkerKind::AutoGenerated, "file"),
        (MarkerKind::UserRegion, "handler"),
    ];

    let before = scan(FIXTURE).expect("fixture markers scan before rustfmt");
    for (kind, segment) in expected {
        assert!(
            before
                .iter()
                .any(|m| m.kind == kind && m.segment == segment),
            "fixture missing {kind:?} marker segment `{segment}` before rustfmt"
        );
    }

    let tmp = tempfile::tempdir().expect("tempdir");
    let fixture_path = tmp.path().join("markers.rs");
    std::fs::write(&fixture_path, FIXTURE).expect("write fixture");
    let instructions_dir = tmp.path().join("instructions");
    std::fs::create_dir(&instructions_dir).expect("create instructions dir");
    std::fs::write(instructions_dir.join("initialize.rs"), "").expect("write module stub");

    let output = Command::new("rustfmt")
        .arg("--edition=2021")
        .arg(&fixture_path)
        .output()
        .expect("rustfmt must be installed with the Rust toolchain");
    assert!(
        output.status.success(),
        "rustfmt failed:\nstdout={}\nstderr={}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );

    let formatted = std::fs::read_to_string(&fixture_path).expect("read formatted fixture");
    let after = scan(&formatted).expect("markers scan after rustfmt");
    assert_eq!(
        after.len(),
        before.len(),
        "rustfmt changed marker count; formatted fixture:\n{formatted}"
    );
    for (kind, segment) in expected {
        assert!(
            after.iter().any(|m| m.kind == kind && m.segment == segment),
            "rustfmt dropped {kind:?} marker segment `{segment}`; formatted fixture:\n{formatted}"
        );
    }
}
