//! Golden test: `rustfmt --edition=2021` must preserve every documented
//! marker segment (cf. ADR-0004 §4 and `docs/reference/markers.md` §5).
//!
//! For each fixture under `tests/fixtures/markers/`:
//!   1. Scan the original file with `rustpatch::marker::scan` to record the
//!      marker pairs.
//!   2. Run `rustfmt --edition=2021` on a copy.
//!   3. Re-scan the formatted output. Assert that:
//!      - the same number of marker pairs exist,
//!      - segments are in the same order,
//!      - each segment's `kind` and `version` is preserved.
//!   4. Apply a no-op `Patch` to every auto-generated segment in the
//!      formatted file. This must succeed (round-trip survives `apply`).
//!
//! If `rustfmt` is not available, the test prints a skip message and
//! returns — it does NOT fail. Keeps the suite green on minimal dev boxes.
//!
//! Owned by qa-integrator (R5).

use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

use sunscreen::rustpatch::{apply, scan, MarkerKind, Patch};

fn fixtures_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("fixtures")
        .join("markers")
}

fn rustfmt_available() -> bool {
    Command::new("rustfmt")
        .arg("--version")
        .output()
        .map(|o| o.status.success())
        .unwrap_or(false)
}

/// Run `rustfmt --edition=2021` on `path` in place. Returns the formatted
/// contents.
fn run_rustfmt(path: &Path) -> Result<String, String> {
    let out = Command::new("rustfmt")
        .args(["--edition", "2021"])
        .arg(path)
        .output()
        .map_err(|e| format!("failed to spawn rustfmt: {e}"))?;
    if !out.status.success() {
        return Err(format!(
            "rustfmt failed (exit={:?}): {}",
            out.status.code(),
            String::from_utf8_lossy(&out.stderr)
        ));
    }
    fs::read_to_string(path).map_err(|e| format!("read after rustfmt: {e}"))
}

fn check_fixture(name: &str) {
    let src_path = fixtures_dir().join(name);
    let src = fs::read_to_string(&src_path).unwrap_or_else(|e| panic!("read fixture {name}: {e}"));

    let original_markers = scan(&src)
        .unwrap_or_else(|e| panic!("fixture {name} has invalid markers BEFORE rustfmt: {e}"));
    assert!(
        !original_markers.is_empty(),
        "fixture {name} contains no markers — bad fixture",
    );

    // Copy fixture to a temp file so rustfmt edits don't touch the source tree.
    let tmp = tempfile::tempdir().expect("tempdir");
    let work_path = tmp.path().join(name);
    fs::write(&work_path, &src).unwrap();

    let formatted = match run_rustfmt(&work_path) {
        Ok(s) => s,
        Err(e) => panic!("rustfmt failed on fixture {name}: {e}"),
    };

    let formatted_markers = scan(&formatted).unwrap_or_else(|e| {
        panic!(
            "fixture {name}: rustfmt produced output with invalid markers: {e}\n--- formatted ---\n{formatted}",
        )
    });

    assert_eq!(
        original_markers.len(),
        formatted_markers.len(),
        "fixture {name}: marker count changed after rustfmt (before={}, after={})\nformatted:\n{formatted}",
        original_markers.len(),
        formatted_markers.len(),
    );

    for (i, (before, after)) in original_markers
        .iter()
        .zip(formatted_markers.iter())
        .enumerate()
    {
        assert_eq!(
            before.segment, after.segment,
            "fixture {name}: segment order changed at index {i} ({} -> {})",
            before.segment, after.segment,
        );
        assert_eq!(
            before.kind, after.kind,
            "fixture {name}: kind changed for segment {} ({:?} -> {:?})",
            before.segment, before.kind, after.kind,
        );
        assert_eq!(
            before.version, after.version,
            "fixture {name}: version changed for segment {} ({} -> {})",
            before.segment, before.version, after.version,
        );
    }

    // Round-trip apply: rewrite every auto-generated segment with its own body.
    // This proves `apply` still locates and replaces regions after rustfmt.
    let patches: Vec<Patch> = formatted_markers
        .iter()
        .filter(|m| m.kind == MarkerKind::AutoGenerated)
        .map(|m| {
            // Preserve the existing body lines verbatim (no-op patch).
            let body: Vec<String> = formatted
                .lines()
                .skip(m.begin + 1)
                .take(m.end - m.begin - 1)
                .map(str::to_string)
                .collect();
            Patch {
                segment: m.segment.clone(),
                lines: body,
            }
        })
        .collect();

    let reapplied = apply(&formatted, &patches)
        .unwrap_or_else(|e| panic!("fixture {name}: apply after rustfmt failed: {e}"));

    // Idempotent no-op: the file should be byte-identical after re-applying its own body.
    assert_eq!(
        reapplied, formatted,
        "fixture {name}: no-op apply changed the formatted file"
    );

    // And re-scan after apply.
    let final_markers =
        scan(&reapplied).unwrap_or_else(|e| panic!("fixture {name}: scan after apply failed: {e}"));
    assert_eq!(final_markers.len(), formatted_markers.len());
}

#[test]
fn rustfmt_preserves_dispatch_segment() {
    if !rustfmt_available() {
        eprintln!("SKIP: rustfmt not installed");
        return;
    }
    check_fixture("lib_dispatch.rs");
}

#[test]
fn rustfmt_preserves_instructions_segment() {
    if !rustfmt_available() {
        eprintln!("SKIP: rustfmt not installed");
        return;
    }
    check_fixture("instructions_mod.rs");
}

#[test]
fn rustfmt_preserves_accounts_segment() {
    if !rustfmt_available() {
        eprintln!("SKIP: rustfmt not installed");
        return;
    }
    check_fixture("state_mod.rs");
}

#[test]
fn rustfmt_preserves_state_segment() {
    if !rustfmt_available() {
        eprintln!("SKIP: rustfmt not installed");
        return;
    }
    check_fixture("state_vault.rs");
}

#[test]
fn rustfmt_preserves_events_segment() {
    if !rustfmt_available() {
        eprintln!("SKIP: rustfmt not installed");
        return;
    }
    check_fixture("events.rs");
}

#[test]
fn rustfmt_preserves_error_variants_segment() {
    if !rustfmt_available() {
        eprintln!("SKIP: rustfmt not installed");
        return;
    }
    check_fixture("errors.rs");
}

#[test]
fn rustfmt_preserves_file_and_handler_segments() {
    if !rustfmt_available() {
        eprintln!("SKIP: rustfmt not installed");
        return;
    }
    check_fixture("instruction_file.rs");
}
