//! Auto-generated by sunscreen — do not edit by hand.
//! Re-rendered by `sunscreen scaffold instruction` on every run.

// === sunscreen:auto-generated:begin segment=instructions version=1 generator=cli ===
// === sunscreen:auto-generated:end segment=instructions ===
