//! Auto-generated by sunscreen. Edit user regions only.

// === sunscreen:auto-generated:begin segment=instructions version=1 generator=cli ===
// === sunscreen:auto-generated:end segment=instructions ===
