//! Marker scan + apply.
//!
//! Line-oriented string scan. No regex.

use thiserror::Error;

/// Kind of marker pair.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MarkerKind {
    /// CLI-owned region. Body is rewritten by [`apply`].
    AutoGenerated,
    /// User-owned region. Body is preserved.
    UserRegion,
}

/// Resolved marker pair.
///
/// `begin` and `end` are zero-based **line indices** (not byte offsets).
/// `begin` points at the begin-marker line; `end` points at the end-marker
/// line. The replaceable body lives in `(begin, end)` (exclusive both ends).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Marker {
    pub segment: String,
    pub version: u32,
    pub begin: usize,
    pub end: usize,
    pub kind: MarkerKind,
}

/// A single patch targeting an auto-generated segment.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Patch {
    pub segment: String,
    /// Replacement body lines. Each entry becomes one line in the output
    /// (no trailing newline characters; `apply` re-joins with `\n`).
    pub lines: Vec<String>,
}

/// Errors produced by [`scan`] / [`apply`].
#[derive(Debug, Error, PartialEq, Eq)]
pub enum RustpatchError {
    #[error("malformed marker on line {line}: {detail}")]
    Malformed { line: usize, detail: String },
    #[error("unbalanced marker for segment `{segment}` (line {line})")]
    Unbalanced { segment: String, line: usize },
    #[error("duplicate marker for segment `{segment}` (line {line})")]
    Duplicate { segment: String, line: usize },
    #[error("patch targets unknown segment `{0}`")]
    UnknownSegment(String),
    #[error("patch targets a user-region segment `{0}` (forbidden)")]
    UserRegionPatch(String),
}

/// Scan `source` for marker pairs, returning them in source order.
pub fn scan(source: &str) -> Result<Vec<Marker>, RustpatchError> {
    // First pass: collect every marker line as a partial record.
    enum Half {
        AgBegin { segment: String, version: u32 },
        AgEnd { segment: String },
        UrBegin { segment: String },
        UrEnd { segment: String },
    }

    let mut halves: Vec<(usize, Half)> = Vec::new();
    for (idx, raw) in source.lines().enumerate() {
        let line = raw.trim_start();
        // All markers start with `// ===`.
        let Some(rest) = strip_marker_prefix(line) else {
            continue;
        };
        let rest = rest.trim();

        if let Some(after) = rest.strip_prefix("sunscreen:auto-generated:begin") {
            let attrs = parse_attrs(after, idx)?;
            let segment = require_attr(&attrs, "segment", idx)?;
            let version_raw = require_attr(&attrs, "version", idx)?;
            let version: u32 = version_raw.parse().map_err(|_| RustpatchError::Malformed {
                line: idx + 1,
                detail: format!("version `{version_raw}` is not a u32"),
            })?;
            halves.push((idx, Half::AgBegin { segment, version }));
        } else if let Some(after) = rest.strip_prefix("sunscreen:auto-generated:end") {
            let attrs = parse_attrs(after, idx)?;
            let segment = require_attr(&attrs, "segment", idx)?;
            halves.push((idx, Half::AgEnd { segment }));
        } else if let Some(after) = rest.strip_prefix("sunscreen:user-region:begin") {
            let attrs = parse_attrs(after, idx)?;
            let segment = require_attr(&attrs, "segment", idx)?;
            halves.push((idx, Half::UrBegin { segment }));
        } else if let Some(after) = rest.strip_prefix("sunscreen:user-region:end") {
            let attrs = parse_attrs(after, idx)?;
            let segment = require_attr(&attrs, "segment", idx)?;
            halves.push((idx, Half::UrEnd { segment }));
        }
        // Otherwise: a `// ===` comment that isn't a sunscreen marker. Ignore.
    }

    // Second pass: pair them up. We require strict LIFO matching per kind:
    // every begin must be closed by the next end of the same kind+segment
    // before any other begin of the same segment opens.
    let mut markers: Vec<Marker> = Vec::new();
    // Stack tracks open begins so we can detect unbalanced pairs cleanly.
    let mut stack: Vec<(usize, MarkerKind, String, u32)> = Vec::new();

    for (line, half) in halves {
        match half {
            Half::AgBegin { segment, version } => {
                if stack
                    .iter()
                    .any(|(_, k, s, _)| *k == MarkerKind::AutoGenerated && s == &segment)
                {
                    return Err(RustpatchError::Duplicate {
                        segment,
                        line: line + 1,
                    });
                }
                stack.push((line, MarkerKind::AutoGenerated, segment, version));
            }
            Half::UrBegin { segment } => {
                if stack
                    .iter()
                    .any(|(_, k, s, _)| *k == MarkerKind::UserRegion && s == &segment)
                {
                    return Err(RustpatchError::Duplicate {
                        segment,
                        line: line + 1,
                    });
                }
                stack.push((line, MarkerKind::UserRegion, segment, 0));
            }
            Half::AgEnd { segment } => {
                // Strict LIFO: an end must close the MOST RECENT open begin,
                // and that begin must match this end's kind+segment. Crossing
                // pairs (begin a; begin b; end a; end b) are rejected.
                let Some((begin, kind, seg, ver)) = stack.pop() else {
                    return Err(RustpatchError::Unbalanced {
                        segment,
                        line: line + 1,
                    });
                };
                if kind != MarkerKind::AutoGenerated || seg != segment {
                    return Err(RustpatchError::Unbalanced {
                        segment,
                        line: line + 1,
                    });
                }
                markers.push(Marker {
                    segment: seg,
                    version: ver,
                    begin,
                    end: line,
                    kind,
                });
            }
            Half::UrEnd { segment } => {
                // Strict LIFO (see AgEnd above).
                let Some((begin, kind, seg, _)) = stack.pop() else {
                    return Err(RustpatchError::Unbalanced {
                        segment,
                        line: line + 1,
                    });
                };
                if kind != MarkerKind::UserRegion || seg != segment {
                    return Err(RustpatchError::Unbalanced {
                        segment,
                        line: line + 1,
                    });
                }
                markers.push(Marker {
                    segment: seg,
                    version: 0,
                    begin,
                    end: line,
                    kind,
                });
            }
        }
    }

    if let Some((line, _kind, segment, _)) = stack.into_iter().next() {
        return Err(RustpatchError::Unbalanced {
            segment,
            line: line + 1,
        });
    }

    markers.sort_by_key(|m| m.begin);

    // Post-pass: reject sequential duplicates (same kind+segment appears more
    // than once in the resolved list).
    {
        use std::collections::HashSet;
        let mut seen: HashSet<(u8, String)> = HashSet::new();
        for m in &markers {
            let kind_key: u8 = match m.kind {
                MarkerKind::AutoGenerated => 0,
                MarkerKind::UserRegion => 1,
            };
            if !seen.insert((kind_key, m.segment.clone())) {
                return Err(RustpatchError::Duplicate {
                    segment: m.segment.clone(),
                    line: m.begin + 1,
                });
            }
        }
    }

    Ok(markers)
}

/// Apply `patches` to `source`, returning the rewritten source.
///
/// Each patch's `segment` must match an `AutoGenerated` marker present in
/// `source`. User-region segments are read-only; patching one returns
/// [`RustpatchError::UserRegionPatch`]. Unknown segments return
/// [`RustpatchError::UnknownSegment`].
///
/// Idempotency: `apply(apply(s, p), p) == apply(s, p)`.
pub fn apply(source: &str, patches: &[Patch]) -> Result<String, RustpatchError> {
    let markers = scan(source)?;

    // Resolve every patch up-front.
    let mut planned: Vec<(usize, usize, &[String])> = Vec::with_capacity(patches.len());
    for patch in patches {
        let m = markers
            .iter()
            .find(|m| m.segment == patch.segment)
            .ok_or_else(|| RustpatchError::UnknownSegment(patch.segment.clone()))?;
        if m.kind == MarkerKind::UserRegion {
            return Err(RustpatchError::UserRegionPatch(patch.segment.clone()));
        }
        planned.push((m.begin, m.end, patch.lines.as_slice()));
    }
    planned.sort_by_key(|(b, _, _)| *b);

    // Detect overlapping ranges (should never happen — scan is non-overlap
    // for same-segment, but a defensive check is cheap).
    for w in planned.windows(2) {
        if w[0].1 >= w[1].0 {
            return Err(RustpatchError::Malformed {
                line: w[1].0 + 1,
                detail: "overlapping patch ranges".to_string(),
            });
        }
    }

    let lines: Vec<&str> = source.lines().collect();
    let mut out: Vec<String> = Vec::with_capacity(lines.len() + 16);
    let mut cursor = 0usize;
    for (begin, end, body) in planned {
        // Copy through the begin-marker line itself.
        while cursor <= begin {
            out.push(lines[cursor].to_string());
            cursor += 1;
        }
        // Skip old body.
        cursor = end;
        // Inject new body verbatim.
        for line in body {
            out.push(line.clone());
        }
        // The end-marker line will be copied on next iteration / tail.
    }
    while cursor < lines.len() {
        out.push(lines[cursor].to_string());
        cursor += 1;
    }

    let mut result = out.join("\n");
    // Preserve a trailing newline if the input had one.
    if source.ends_with('\n') {
        result.push('\n');
    }
    Ok(result)
}

// ---------------------------------------------------------------------------
// helpers
// ---------------------------------------------------------------------------

/// Strip the leading `// ===` (with arbitrary whitespace around the slashes
/// and the equals sequence). Returns the slice after the `===`.
fn strip_marker_prefix(line: &str) -> Option<&str> {
    let line = line.strip_prefix("//")?;
    let line = line.trim_start();
    line.strip_prefix("===")
}

/// Parse a marker tail like
/// `segment=foo version=1 generator=cli ===`
/// into (key, value) pairs. The trailing `===` and any whitespace is
/// tolerated.
fn parse_attrs(s: &str, line: usize) -> Result<Vec<(String, String)>, RustpatchError> {
    // Drop trailing `===` if present.
    let s = s.trim();
    let s = s.strip_suffix("===").unwrap_or(s).trim();

    let mut out = Vec::new();
    for tok in s.split_whitespace() {
        let Some((k, v)) = tok.split_once('=') else {
            return Err(RustpatchError::Malformed {
                line: line + 1,
                detail: format!("attribute `{tok}` is not key=value"),
            });
        };
        out.push((k.to_string(), v.to_string()));
    }
    Ok(out)
}

fn require_attr(
    attrs: &[(String, String)],
    key: &str,
    line: usize,
) -> Result<String, RustpatchError> {
    attrs
        .iter()
        .find(|(k, _)| k == key)
        .map(|(_, v)| v.clone())
        .ok_or_else(|| RustpatchError::Malformed {
            line: line + 1,
            detail: format!("missing required attribute `{key}`"),
        })
}

// ---------------------------------------------------------------------------
// tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn scan_empty_source() {
        let m = scan("").unwrap();
        assert!(m.is_empty());
    }

    #[test]
    fn scan_no_markers() {
        let src = "fn main() {}\n";
        assert!(scan(src).unwrap().is_empty());
    }

    #[test]
    fn scan_single_auto_generated() {
        let src = "\
prefix
    // === sunscreen:auto-generated:begin segment=foo version=2 ===
body1
body2
    // === sunscreen:auto-generated:end segment=foo ===
suffix
";
        let m = scan(src).unwrap();
        assert_eq!(m.len(), 1);
        assert_eq!(m[0].segment, "foo");
        assert_eq!(m[0].version, 2);
        assert_eq!(m[0].kind, MarkerKind::AutoGenerated);
        assert_eq!(m[0].begin, 1);
        assert_eq!(m[0].end, 4);
    }

    #[test]
    fn scan_user_region() {
        let src = "\
// === sunscreen:user-region:begin segment=handler ===
let x = 1;
// === sunscreen:user-region:end segment=handler ===
";
        let m = scan(src).unwrap();
        assert_eq!(m.len(), 1);
        assert_eq!(m[0].kind, MarkerKind::UserRegion);
        assert_eq!(m[0].segment, "handler");
    }

    #[test]
    fn scan_multiple_segments() {
        let src = "\
// === sunscreen:auto-generated:begin segment=a version=1 ===
// === sunscreen:auto-generated:end segment=a ===
// === sunscreen:auto-generated:begin segment=b version=1 ===
// === sunscreen:auto-generated:end segment=b ===
";
        let m = scan(src).unwrap();
        assert_eq!(m.len(), 2);
        assert_eq!(m[0].segment, "a");
        assert_eq!(m[1].segment, "b");
    }

    #[test]
    fn scan_unbalanced_missing_end() {
        let src = "// === sunscreen:auto-generated:begin segment=foo version=1 ===\n";
        let err = scan(src).unwrap_err();
        assert!(matches!(err, RustpatchError::Unbalanced { .. }));
    }

    #[test]
    fn scan_unbalanced_stray_end() {
        let src = "// === sunscreen:auto-generated:end segment=foo ===\n";
        let err = scan(src).unwrap_err();
        assert!(matches!(err, RustpatchError::Unbalanced { .. }));
    }

    #[test]
    fn scan_rejects_crossing_pairs() {
        // begin a; begin b; end a; end b — crossing (non-LIFO) nesting must
        // be rejected as unbalanced.
        let src = "\
// === sunscreen:auto-generated:begin segment=a version=1 ===
// === sunscreen:auto-generated:begin segment=b version=1 ===
// === sunscreen:auto-generated:end segment=a ===
// === sunscreen:auto-generated:end segment=b ===
";
        let err = scan(src).unwrap_err();
        assert!(matches!(err, RustpatchError::Unbalanced { .. }));
    }

    #[test]
    fn scan_duplicate_segment() {
        let src = "\
// === sunscreen:auto-generated:begin segment=foo version=1 ===
// === sunscreen:auto-generated:begin segment=foo version=1 ===
// === sunscreen:auto-generated:end segment=foo ===
// === sunscreen:auto-generated:end segment=foo ===
";
        let err = scan(src).unwrap_err();
        assert!(matches!(err, RustpatchError::Duplicate { .. }));
    }

    #[test]
    fn scan_sequential_duplicate_segment() {
        let src = "\
// === sunscreen:auto-generated:begin segment=foo version=1 ===
// body
// === sunscreen:auto-generated:end segment=foo ===
// === sunscreen:auto-generated:begin segment=foo version=1 ===
// body2
// === sunscreen:auto-generated:end segment=foo ===
";
        let err = scan(src).unwrap_err();
        assert!(matches!(err, RustpatchError::Duplicate { .. }));
    }

    #[test]
    fn scan_malformed_missing_segment() {
        let src = "// === sunscreen:auto-generated:begin version=1 ===\n";
        let err = scan(src).unwrap_err();
        assert!(matches!(err, RustpatchError::Malformed { .. }));
    }

    #[test]
    fn apply_replaces_body() {
        let src = "\
header
// === sunscreen:auto-generated:begin segment=foo version=1 ===
old1
old2
// === sunscreen:auto-generated:end segment=foo ===
footer
";
        let patches = vec![Patch {
            segment: "foo".to_string(),
            lines: vec!["new1".to_string(), "new2".to_string(), "new3".to_string()],
        }];
        let out = apply(src, &patches).unwrap();
        let expected = "\
header
// === sunscreen:auto-generated:begin segment=foo version=1 ===
new1
new2
new3
// === sunscreen:auto-generated:end segment=foo ===
footer
";
        assert_eq!(out, expected);
    }

    #[test]
    fn apply_is_idempotent() {
        let src = "\
// === sunscreen:auto-generated:begin segment=foo version=1 ===
old
// === sunscreen:auto-generated:end segment=foo ===
";
        let patches = vec![Patch {
            segment: "foo".to_string(),
            lines: vec!["L1".to_string(), "L2".to_string()],
        }];
        let once = apply(src, &patches).unwrap();
        let twice = apply(&once, &patches).unwrap();
        assert_eq!(once, twice);
    }

    #[test]
    fn apply_preserves_outside_content() {
        let src = "\
a
b
// === sunscreen:auto-generated:begin segment=foo version=1 ===
x
// === sunscreen:auto-generated:end segment=foo ===
c
d
";
        let patches = vec![Patch {
            segment: "foo".to_string(),
            lines: vec!["y".to_string()],
        }];
        let out = apply(src, &patches).unwrap();
        assert!(out.starts_with("a\nb\n"));
        assert!(out.ends_with("c\nd\n"));
        assert!(out.contains("\ny\n"));
        assert!(!out.contains("\nx\n"));
    }

    #[test]
    fn apply_unknown_segment_errors() {
        let src = "\
// === sunscreen:auto-generated:begin segment=foo version=1 ===
// === sunscreen:auto-generated:end segment=foo ===
";
        let patches = vec![Patch {
            segment: "bar".to_string(),
            lines: vec![],
        }];
        let err = apply(src, &patches).unwrap_err();
        assert!(matches!(err, RustpatchError::UnknownSegment(_)));
    }

    #[test]
    fn apply_user_region_forbidden() {
        let src = "\
// === sunscreen:user-region:begin segment=handler ===
// === sunscreen:user-region:end segment=handler ===
";
        let patches = vec![Patch {
            segment: "handler".to_string(),
            lines: vec![],
        }];
        let err = apply(src, &patches).unwrap_err();
        assert!(matches!(err, RustpatchError::UserRegionPatch(_)));
    }

    #[test]
    fn apply_multiple_patches_in_order() {
        let src = "\
// === sunscreen:auto-generated:begin segment=a version=1 ===
oldA
// === sunscreen:auto-generated:end segment=a ===
middle
// === sunscreen:auto-generated:begin segment=b version=1 ===
oldB
// === sunscreen:auto-generated:end segment=b ===
";
        let patches = vec![
            Patch {
                segment: "b".into(),
                lines: vec!["newB".into()],
            },
            Patch {
                segment: "a".into(),
                lines: vec!["newA".into()],
            },
        ];
        let out = apply(src, &patches).unwrap();
        assert!(out.contains("newA"));
        assert!(out.contains("newB"));
        assert!(!out.contains("oldA"));
        assert!(!out.contains("oldB"));
    }

    #[test]
    fn apply_empty_body() {
        let src = "\
// === sunscreen:auto-generated:begin segment=foo version=1 ===
oldline
// === sunscreen:auto-generated:end segment=foo ===
";
        let patches = vec![Patch {
            segment: "foo".into(),
            lines: vec![],
        }];
        let out = apply(src, &patches).unwrap();
        let expected = "\
// === sunscreen:auto-generated:begin segment=foo version=1 ===
// === sunscreen:auto-generated:end segment=foo ===
";
        assert_eq!(out, expected);
    }
}
